//this is a void function.
function add(){
	var x = 1;
	var y= 2;
	var sum = x+y;
	console.log (sum);
}
//call the function.
 add ()

 function multiply(){
 	var x = 5;
 	var y = 6;
 	var z = 8;
 	var answer = x*y*z;
 	
 return answer


 }


 var results = multiply()

 console.log( results)

 function divide(){
 	var a = 6;
 	var b = 3;
 	var answer = a / b;

 	  return answer
 }

 var divide = divide ()
 console.log(divide)


 function subtract(){
 	var a = 10;
 	var b = 5 ;
 	var answer = a - b;

 	return answer
 }
 	 var minus = subtract ()
 	 console.log(minus)






 